import { binToHex } from '@bitauth/libauth';

import { encodeAddress } from '@rosen-bridge/address-codec';
import {
  decodeBchTransaction,
  getBchUnsignedBytes,
} from '@rosen-chains/bitcoin-cash';

import BitcoinCashRpcNetwork from './bitcoinCashRpcNetwork';
import { boundedInteger, createBitcoinCashRpcTransport } from './transport';
import { BitcoinCashRpcConfig, RpcTransport } from './types';
import { hash } from './validation';

export type BitcoinCashRpcCapability =
  | 'identity'
  | 'block_info'
  | 'block_transactions'
  | 'known_transaction'
  | 'treasury_address'
  | 'treasury_outputs'
  | 'prevout'
  | 'current_output'
  | 'mempool_read'
  | 'wallet_recovery'
  | 'indexed_absence';

export interface BitcoinCashRpcCapabilityResult {
  capability: BitcoinCashRpcCapability;
  status: 'passed' | 'failed' | 'unexercised';
  reason:
    | 'observed'
    | 'missing_sample'
    | 'dependency_unavailable'
    | 'no_usable_sample'
    | 'probe_failed'
    | 'unexpected_presence'
    | 'deadline_exhausted'
    | 'request_limit_exhausted';
}

export interface BitcoinCashRpcProbeOptions {
  config: BitcoinCashRpcConfig;
  samples: {
    treasuryAddress?: string;
    /** Both values identify a known transaction in its current-chain block. */
    blockHash?: string;
    transactionId?: string;
    /** Canonical transaction-hash.output-index identifier. */
    outpoint?: string;
    /** Operator-selected actual transaction hash to check against the mempool. */
    mempoolTransactionId?: string;
    /** Operator-provided canonical unsigned body; never generated by the probe. */
    unsignedRecoveryBody?: Uint8Array;
    /** Operator-selected hash expected to be globally absent. */
    absentTransactionId?: string;
  };
  /** Whole-run deadline; default 30000 ms, maximum 120000 ms. */
  totalTimeoutMs?: number;
  /** Whole-run RPC dispatch ceiling; default 200, maximum 500. */
  maxRequests?: number;
}

export interface BitcoinCashRpcCapabilityReport {
  capabilities: BitcoinCashRpcCapabilityResult[];
  requests: number;
}

const readMethods = new Set([
  'getnetworkinfo',
  'getblockchaininfo',
  'getblockheader',
  'getblockhash',
  'getblock',
  'getrawtransaction',
  'gettransaction',
  'gettxout',
  'getaddressinfo',
  'listunspent',
  'getrawmempool',
  'getbestblockhash',
  'getwalletinfo',
  'listtransactions',
  'getindexinfo',
]);

/**
 * Refuse every RPC outside the fixed observation allowlist before dispatch.
 * @param transport - Transport receiving permitted requests only
 * @returns A read-only transport without wallet or chain mutation methods
 */
export const readOnlyBitcoinCashRpcTransport = (
  transport: RpcTransport,
): RpcTransport => ({
  /**
   * Forward only a listed observational method.
   * @param method - Exact RPC method name
   * @param params - Positional read arguments
   * @returns The underlying result, requiring provider validation
   */
  call: async (method, params) => {
    if (!readMethods.has(method)) throw Error('RPC method is not read-only');
    return transport.call(method, params);
  },
});

/**
 * Exercise bounded provider reads with explicit samples and sanitized results.
 * Invalid configuration or samples reject before the first network request.
 * @param options - Endpoint configuration, operator samples and whole-run limits
 * @param fetcher - Fixture HTTP seam; production callers use the platform fetch
 * @returns Individual observations, never an endpoint readiness verdict
 */
export const probeBitcoinCashRpcCapabilities = async (
  options: BitcoinCashRpcProbeOptions,
  fetcher: typeof fetch = fetch,
): Promise<BitcoinCashRpcCapabilityReport> => {
  const config = {
    ...options.config,
    auth: options.config.auth ? { ...options.config.auth } : undefined,
  };
  const samples = { ...options.samples };
  const totalTimeout = boundedInteger(options.totalTimeoutMs, 30_000, 120_000);
  const maxRequests = boundedInteger(options.maxRequests, 200, 500);
  const timeout = boundedInteger(config.timeoutMs, 10_000, 60_000);
  // Validate transport and provider limits even when no corresponding sample exists.
  createBitcoinCashRpcTransport(config, fetcher);
  for (const id of [
    samples.blockHash,
    samples.transactionId,
    samples.mempoolTransactionId,
    samples.absentTransactionId,
  ]) {
    if (id !== undefined) hash(id);
  }
  if (samples.treasuryAddress !== undefined)
    encodeAddress('bitcoin-cash', samples.treasuryAddress);
  if (samples.outpoint !== undefined) {
    const match = /^([0-9a-f]{64})\.(0|[1-9][0-9]{0,9})$/.exec(
      samples.outpoint,
    );
    if (!match || Number(match[2]) > 0xffffffff)
      throw Error('Invalid capability outpoint sample');
  }
  if (samples.unsignedRecoveryBody !== undefined) {
    if (
      !(samples.unsignedRecoveryBody instanceof Uint8Array) ||
      samples.unsignedRecoveryBody.length > 100_000
    )
      throw Error('Invalid capability recovery sample');
    samples.unsignedRecoveryBody = Uint8Array.from(
      samples.unsignedRecoveryBody,
    );
    const decoded = decodeBchTransaction(samples.unsignedRecoveryBody);
    if (
      decoded.inputs.some((input) => input.unlockingBytecode.length) ||
      binToHex(getBchUnsignedBytes(samples.unsignedRecoveryBody)) !==
        binToHex(samples.unsignedRecoveryBody)
    )
      throw Error('Invalid capability recovery sample');
  }
  const deadline = performance.now() + totalTimeout;
  let requests = 0;
  let exhausted: BitcoinCashRpcCapabilityResult['reason'] | undefined;
  const rpc = readOnlyBitcoinCashRpcTransport({
    /**
     * Bound each awaited request by the remaining shared budget.
     * @param method - Allowlisted read method
     * @param params - Provider-generated positional arguments
     * @returns Validated transport result within the whole-run budget
     */
    call: async (method, params) => {
      const remaining = Math.floor(deadline - performance.now());
      if (remaining < 1) exhausted = 'deadline_exhausted';
      else if (requests >= maxRequests) exhausted = 'request_limit_exhausted';
      if (exhausted) throw Error('Capability probe budget exhausted');
      requests++;
      let result: unknown;
      try {
        result = await createBitcoinCashRpcTransport(
          { ...config, timeoutMs: Math.min(timeout, remaining) },
          fetcher,
        ).call(method, params);
      } catch (error) {
        if (performance.now() >= deadline) exhausted = 'deadline_exhausted';
        throw error;
      }
      if (performance.now() >= deadline) {
        exhausted = 'deadline_exhausted';
        throw Error('Capability probe budget exhausted');
      }
      return result;
    },
  });
  const network = new BitcoinCashRpcNetwork(config, rpc);
  const capabilities: BitcoinCashRpcCapabilityResult[] = [];
  /**
   * Record one probe without retaining its payload or error text.
   * @param capability - Fixed observation identifier
   * @param available - Whether its required sample and predecessor are available
   * @param run - Provider operation returning its evidence status
   * @param missing - Fixed reason for an unavailable sample or dependency
   * @returns Whether this observation passed
   */
  const probe = async (
    capability: BitcoinCashRpcCapability,
    available: boolean,
    run: () => Promise<BitcoinCashRpcCapabilityResult['reason']>,
    missing: BitcoinCashRpcCapabilityResult['reason'] = 'missing_sample',
  ): Promise<boolean> => {
    let reason = exhausted ?? missing;
    let status: BitcoinCashRpcCapabilityResult['status'] = 'unexercised';
    if (available && !exhausted) {
      try {
        reason = await run();
        status =
          reason === 'observed'
            ? 'passed'
            : reason === 'no_usable_sample'
              ? 'unexercised'
              : 'failed';
      } catch {
        reason = exhausted ?? 'probe_failed';
        status = 'failed';
      }
    }
    capabilities.push({ capability, status, reason });
    return status === 'passed';
  };
  const identity = await probe('identity', true, async () => {
    await network.getHeight();
    return 'observed';
  });
  const dependency = identity ? 'missing_sample' : 'dependency_unavailable';
  const block = await probe(
    'block_info',
    identity && samples.blockHash !== undefined,
    async () => {
      await network.getBlockInfo(samples.blockHash!);
      return 'observed';
    },
    dependency,
  );
  const ids = await probe(
    'block_transactions',
    block,
    async () => {
      await network.getBlockTransactionIds(samples.blockHash!);
      return 'observed';
    },
    'dependency_unavailable',
  );
  await probe(
    'known_transaction',
    ids && samples.transactionId !== undefined,
    async () => {
      await network.getTransaction(samples.transactionId!, samples.blockHash!);
      return 'observed';
    },
    ids ? 'missing_sample' : 'dependency_unavailable',
  );
  let boxes = 0;
  const treasury = await probe(
    'treasury_address',
    identity && samples.treasuryAddress !== undefined,
    async () => {
      boxes = (
        await network.getAddressBoxes(
          samples.treasuryAddress!,
          0,
          boundedInteger(config.maxUtxos, 1000, 10_000),
        )
      ).length;
      return 'observed';
    },
    dependency,
  );
  await probe(
    'treasury_outputs',
    treasury,
    async () => (boxes ? 'observed' : 'no_usable_sample'),
    'dependency_unavailable',
  );
  const prevout = await probe(
    'prevout',
    identity && samples.outpoint !== undefined,
    async () => {
      await network.getPrevout(samples.outpoint!);
      return 'observed';
    },
    dependency,
  );
  await probe(
    'current_output',
    prevout,
    async () =>
      (await network.getUtxo(samples.outpoint!))
        ? 'observed'
        : 'no_usable_sample',
    'dependency_unavailable',
  );
  await probe(
    'mempool_read',
    identity && samples.mempoolTransactionId !== undefined,
    async () => {
      await network.isTxInMempool(samples.mempoolTransactionId!);
      return 'observed';
    },
    dependency,
  );
  await probe(
    'wallet_recovery',
    identity && samples.unsignedRecoveryBody !== undefined,
    async () =>
      (await network.findSignedTransaction(samples.unsignedRecoveryBody!))
        ? 'observed'
        : 'no_usable_sample',
    dependency,
  );
  await probe(
    'indexed_absence',
    identity && samples.absentTransactionId !== undefined,
    async () =>
      (await network.getTxConfirmation(samples.absentTransactionId!)) === -1
        ? 'observed'
        : 'unexpected_presence',
    dependency,
  );
  return { capabilities, requests };
};
