import { binToHex } from '@bitauth/libauth';

import {
  BitcoinCashRpcCapabilityReport,
  BitcoinCashRpcError,
  BitcoinCashRpcProbeOptions,
  probeBitcoinCashRpcCapabilities,
  readOnlyBitcoinCashRpcTransport,
} from '../lib';
import { block } from './bitcoinCashRpcTestData';
import {
  address,
  fixture,
  parentId,
  signedId,
  unsigned,
} from './bitcoinCashRpcTestUtils';

/** Operator-selected synthetic absence hash, distinct from every fixture ID. */
const absent = 'fe'.repeat(32);
/** Complete synthetic sample profile, without any live endpoint or credentials. */
const options: BitcoinCashRpcProbeOptions = {
  config: { url: 'http://127.0.0.1:18443', expectedChain: 'regtest' },
  samples: {
    treasuryAddress: address,
    blockHash: block,
    transactionId: signedId,
    outpoint: `${parentId}.0`,
    mempoolTransactionId: signedId,
    unsignedRecoveryBody: unsigned,
    absentTransactionId: absent,
  },
};

/**
 * Adapt existing provider fixtures to real HTTP envelope parsing.
 * @param overrides - Isolated provider response changes
 * @returns HTTP fetch seam and recorded provider calls
 */
const setup = (overrides: Parameters<typeof fixture>[0] = {}) => {
  const f = fixture(overrides);
  /**
   * Reply with matching JSON-RPC identity, including a selected absent sample.
   * @param _url - Unused synthetic destination
   * @param init - Request generated by the real bounded HTTP transport
   * @returns An in-memory JSON-RPC HTTP response
   */
  const fetcher: typeof fetch = async (_url, init) => {
    const { id, method, params } = JSON.parse(String(init?.body));
    let result: unknown = null;
    let error: unknown = null;
    try {
      if (
        params[0] === absent &&
        ['getrawtransaction', 'gettransaction'].includes(method)
      ) {
        f.calls.push({ method, params });
        throw new BitcoinCashRpcError(-5);
      }
      result = await f.transport.call(method, params);
    } catch (caught) {
      if (!(caught instanceof BitcoinCashRpcError)) throw caught;
      error = { code: caught.code, message: 'fixture rejection' };
    }
    return new Response(JSON.stringify({ id, result, error }));
  };
  return { ...f, fetcher };
};

/**
 * Select one fixed capability result for exact assertions.
 * @param report - Sanitized report
 * @param capability - Fixed capability code
 * @returns Matching observation
 */
const result = (report: BitcoinCashRpcCapabilityReport, capability: string) =>
  report.capabilities.find((entry) => entry.capability === capability);

describe('readOnlyBitcoinCashRpcTransport', () => {
  describe('call', () => {
    /**
     * @target readOnlyBitcoinCashRpcTransport.call permits a listed read
     * @dependencies Recorded transport spy
     * @scenario Call getnetworkinfo with empty arguments.
     * @expected Forward the exact request and return the result.
     */
    it('permits a listed read', async () => {
      const call = vi.fn().mockResolvedValue({ version: 1 });
      await expect(
        readOnlyBitcoinCashRpcTransport({ call }).call('getnetworkinfo', []),
      ).resolves.toEqual({ version: 1 });
      expect(call).toHaveBeenCalledWith('getnetworkinfo', []);
    });
    /**
     * @target readOnlyBitcoinCashRpcTransport.call refuses %s before dispatch
     * @dependencies Recorded transport spy
     * @scenario Attempt one forbidden method per vector.
     * @expected Reject without contacting the underlying transport.
     */
    it.each([
      'sendrawtransaction',
      'importaddress',
      'rescanblockchain',
      'getnewaddress',
      'signrawtransactionwithwallet',
      'generatetoaddress',
      'unknown',
    ])('refuses %s before dispatch', async (method) => {
      const call = vi.fn();
      await expect(
        readOnlyBitcoinCashRpcTransport({ call }).call(method, []),
      ).rejects.toThrow();
      expect(call).not.toHaveBeenCalled();
    });
  });
});

describe('probeBitcoinCashRpcCapabilities', () => {
  afterEach(() => vi.restoreAllMocks());
  /**
   * @target probeBitcoinCashRpcCapabilities skips a failed block's dependents
   * @dependencies Isolated malformed header fixture
   * @scenario Fail block header validation while retaining other valid samples.
   * @expected Skip block IDs and transaction reads; independent prevout passes.
   */
  it("skips a failed block's dependents", async () => {
    const f = setup({
      mutate: (method, value) => (method === 'getblockheader' ? {} : value),
    });
    const report = await probeBitcoinCashRpcCapabilities(options, f.fetcher);
    expect(result(report, 'block_info')?.status).toEqual('failed');
    expect(result(report, 'block_transactions')?.status).toEqual('unexercised');
    expect(result(report, 'known_transaction')?.status).toEqual('unexercised');
    expect(result(report, 'prevout')?.status).toEqual('passed');
    expect(f.calls.map((call) => call.method)).not.toContain('getblock');
  });
  /**
   * @target probeBitcoinCashRpcCapabilities rejects unqualified absence
   * @dependencies Isolated unsynced txindex fixture
   * @scenario Return not-found replies but an unsynced index.
   * @expected Absence fails rather than passing or becoming unexercised.
   */
  it('rejects unqualified absence', async () => {
    const f = setup({
      mutate: (method, value) =>
        method === 'getindexinfo'
          ? { txindex: { synced: false, best_block_height: 100 } }
          : value,
    });
    const report = await probeBitcoinCashRpcCapabilities(options, f.fetcher);
    expect(result(report, 'indexed_absence')).toMatchObject({
      status: 'failed',
      reason: 'probe_failed',
    });
  });
  /**
   * @target probeBitcoinCashRpcCapabilities exercises all supplied evidence
   * @dependencies Existing provider fixtures and real HTTP envelope transport
   * @scenario Supply each sample, recover signed bytes and verify indexed absence.
   * @expected Eleven passed observations and bounded read-only dispatches.
   */
  it('exercises all supplied evidence', async () => {
    const f = setup();
    const report = await probeBitcoinCashRpcCapabilities(options, f.fetcher);
    expect(report.capabilities).toHaveLength(11);
    expect(
      report.capabilities.every((entry) => entry.status === 'passed'),
    ).toEqual(true);
    expect(report.requests).toEqual(f.calls.length);
    expect(report.requests).toBeLessThanOrEqual(200);
    expect(f.calls.map((call) => call.method)).toContain('getindexinfo');
    expect(f.calls.map((call) => call.method)).toContain('listtransactions');
  });
  /**
   * @target probeBitcoinCashRpcCapabilities leaves missing samples unexercised
   * @dependencies Identity fixtures
   * @scenario Supply no operator samples.
   * @expected Only identity passes and only two identity requests occur.
   */
  it('leaves missing samples unexercised', async () => {
    const f = setup();
    const report = await probeBitcoinCashRpcCapabilities(
      { ...options, samples: {} },
      f.fetcher,
    );
    expect(report.requests).toEqual(2);
    expect(result(report, 'identity')?.status).toEqual('passed');
    expect(
      report.capabilities
        .slice(1)
        .every((entry) => entry.status === 'unexercised'),
    ).toEqual(true);
  });
  /**
   * @target probeBitcoinCashRpcCapabilities stops after identity failure
   * @dependencies Isolated client identity mutation
   * @scenario Return a Bitcoin Core client identifier.
   * @expected Identity fails; every dependent observation remains unexercised.
   */
  it('stops after identity failure', async () => {
    const f = setup({
      mutate: (method, value) =>
        method === 'getnetworkinfo'
          ? { subversion: '/Satoshi:29.1.0/' }
          : value,
    });
    const report = await probeBitcoinCashRpcCapabilities(options, f.fetcher);
    expect(result(report, 'identity')?.status).toEqual('failed');
    expect(
      report.capabilities
        .slice(1)
        .every((entry) => entry.status === 'unexercised'),
    ).toEqual(true);
    expect(report.requests).toEqual(1);
  });
  /**
   * @target probeBitcoinCashRpcCapabilities distinguishes empty treasury outputs
   * @dependencies Empty listunspent response
   * @scenario Recognize the imported address with no current wallet outputs.
   * @expected Address passes but output evidence remains unexercised.
   */
  it('distinguishes empty treasury outputs', async () => {
    const f = setup({
      mutate: (method, value) => (method === 'listunspent' ? [] : value),
    });
    const report = await probeBitcoinCashRpcCapabilities(options, f.fetcher);
    expect(result(report, 'treasury_address')?.status).toEqual('passed');
    expect(result(report, 'treasury_outputs')).toMatchObject({
      status: 'unexercised',
      reason: 'no_usable_sample',
    });
  });
  /**
   * @target probeBitcoinCashRpcCapabilities distinguishes spent current outputs
   * @dependencies Null current output response
   * @scenario Resolve valid parent bytes whose current output is spent.
   * @expected Prevout passes but current output remains unexercised.
   */
  it('distinguishes spent current outputs', async () => {
    const f = setup({ current: null });
    const report = await probeBitcoinCashRpcCapabilities(options, f.fetcher);
    expect(result(report, 'prevout')?.status).toEqual('passed');
    expect(result(report, 'current_output')).toMatchObject({
      status: 'unexercised',
      reason: 'no_usable_sample',
    });
  });
  /**
   * @target probeBitcoinCashRpcCapabilities requires recovered matching bytes
   * @dependencies Empty retained wallet history
   * @scenario Scan a stable empty wallet using a supplied canonical body.
   * @expected Wallet recovery remains unexercised rather than passing.
   */
  it('requires recovered matching bytes', async () => {
    const f = setup({ history: [] });
    const report = await probeBitcoinCashRpcCapabilities(options, f.fetcher);
    expect(result(report, 'wallet_recovery')).toMatchObject({
      status: 'unexercised',
      reason: 'no_usable_sample',
    });
  });
  /**
   * @target probeBitcoinCashRpcCapabilities requires actual indexed absence
   * @dependencies Real getTxConfirmation positive mempool path
   * @scenario Select a known signed mempool transaction as the absent sample.
   * @expected Fail absence with unexpected_presence; do not claim an index test.
   */
  it('requires actual indexed absence', async () => {
    const f = setup();
    const report = await probeBitcoinCashRpcCapabilities(
      { ...options, samples: { absentTransactionId: signedId } },
      f.fetcher,
    );
    expect(result(report, 'indexed_absence')).toMatchObject({
      status: 'failed',
      reason: 'unexpected_presence',
    });
    expect(f.calls.map((call) => call.method)).not.toContain('getindexinfo');
  });
  /**
   * @target probeBitcoinCashRpcCapabilities enforces a shared request ceiling
   * @dependencies Full synthetic samples with three permitted requests
   * @scenario Exhaust the ceiling during the block identity read.
   * @expected Fail that group, skip subsequent groups and dispatch exactly three.
   */
  it('enforces a shared request ceiling', async () => {
    const f = setup();
    const report = await probeBitcoinCashRpcCapabilities(
      { ...options, maxRequests: 3 },
      f.fetcher,
    );
    expect(report.requests).toEqual(3);
    expect(f.calls).toHaveLength(3);
    expect(result(report, 'block_info')).toMatchObject({
      status: 'failed',
      reason: 'request_limit_exhausted',
    });
    expect(
      report.capabilities
        .slice(2)
        .every((entry) => entry.status === 'unexercised'),
    ).toEqual(true);
  });
  /**
   * @target probeBitcoinCashRpcCapabilities rejects late responses
   * @dependencies Monotonic clock spy and real envelope parsing
   * @scenario Let the final identity response arrive after the total deadline.
   * @expected Identity fails after two requests without another dispatch check.
   */
  it('rejects late responses', async () => {
    let now = 0;
    vi.spyOn(performance, 'now').mockImplementation(() => now);
    const f = setup();
    const report = await probeBitcoinCashRpcCapabilities(
      { ...options, samples: {}, totalTimeoutMs: 10 },
      async (...args) => {
        const response = await f.fetcher(...args);
        if (f.calls.length === 2) now = 11;
        return response;
      },
    );
    expect(report.requests).toEqual(2);
    expect(result(report, 'identity')).toMatchObject({
      status: 'failed',
      reason: 'deadline_exhausted',
    });
  });
  /**
   * @target probeBitcoinCashRpcCapabilities aborts a pending request
   * @dependencies Abort-aware fetch seam and fake timers
   * @scenario Keep fetch pending beyond a total budget shorter than request timeout.
   * @expected Transport abort is awaited; only one request occurs.
   */
  it('aborts a pending request', async () => {
    vi.useFakeTimers({ toFake: ['setTimeout', 'clearTimeout', 'performance'] });
    let aborted = false;
    try {
      const run = probeBitcoinCashRpcCapabilities(
        { ...options, totalTimeoutMs: 10 },
        async (_url, init) =>
          new Promise((_resolve, reject) => {
            init!.signal!.addEventListener('abort', () => {
              aborted = true;
              reject(Error('fixture abort'));
            });
          }),
      );
      await vi.advanceTimersByTimeAsync(10);
      const report = await run;
      expect(aborted).toEqual(true);
      expect(report.requests).toEqual(1);
      expect(result(report, 'identity')).toMatchObject({
        status: 'failed',
        reason: 'deadline_exhausted',
      });
    } finally {
      vi.useRealTimers();
    }
  });
  /**
   * @target probeBitcoinCashRpcCapabilities sanitizes failures and sample material
   * @dependencies Error containing synthetic credentials and raw unsigned bytes
   * @scenario Throw secret-bearing HTTP failure text.
   * @expected Report contains only fixed codes and request count.
   */
  it('sanitizes failures and sample material', async () => {
    const secret = 'fixture-private-password';
    const report = await probeBitcoinCashRpcCapabilities(
      {
        ...options,
        config: {
          ...options.config,
          auth: { username: 'fixture-user', password: secret },
        },
      },
      async () => {
        throw Error(`${secret} ${options.config.url} ${binToHex(unsigned)}`);
      },
    );
    expect(report.capabilities[0]).toEqual({
      capability: 'identity',
      status: 'failed',
      reason: 'probe_failed',
    });
    expect(JSON.stringify(report)).not.toContain(secret);
    expect(JSON.stringify(report)).not.toContain(options.config.url);
    expect(JSON.stringify(report)).not.toContain(binToHex(unsigned));
  });
  /**
   * @target probeBitcoinCashRpcCapabilities rejects invalid %s before dispatch
   * @dependencies Fetch spy with independently invalid input vectors
   * @scenario Supply one malformed limit or sample per vector.
   * @expected Reject before any network call, including unused provider limits.
   */
  it.each([
    ['request count', { maxRequests: 501 }],
    ['total deadline', { totalTimeoutMs: 0 }],
    ['provider limit', { config: { ...options.config, maxUtxos: 0 } }],
    ['endpoint', { config: { ...options.config, url: 'file:///fixture' } }],
    ['hash', { samples: { transactionId: 'bad' } }],
    ['outpoint', { samples: { outpoint: `${parentId}.4294967296` } }],
    ['address', { samples: { treasuryAddress: 'bad' } }],
    ['recovery body', { samples: { unsignedRecoveryBody: Uint8Array.of(1) } }],
  ] as const)('rejects invalid %s before dispatch', async (_name, invalid) => {
    const fetcher = vi.fn();
    await expect(
      probeBitcoinCashRpcCapabilities({ ...options, ...invalid }, fetcher),
    ).rejects.toThrow();
    expect(fetcher).not.toHaveBeenCalled();
  });
});
