---
# all time related configs are in seconds (timeout, interval, ...)

api:
  port: 8080 # service deployment port
  host: 'localhost' # service listening host
  apiKeyHash: '' # blake2b hash of Api-Key
  jsonBodyLimit: 50
  isManualTxRequestActive: false
  allowedOrigins: [] # List of allowed origins for CORS headers
  maxRequestsPerMinute: 100_000
bitcoin:
  networkType: 'mainnet' # Bitcoin network type [testnet, mainnet]
  chainNetwork: 'esplora' # 'esplora'
  esplora:
    url: 'https://blockstream.info'
    timeout: 8
  bankPublicKey: '' # corresponding public key of lock address
  txFeeSlippage: 10 # allowed slippage percentage for tx fees
  confirmation: # required block confirmation
    observation: 6 # an observation transaction (lock transaction) on Bitcoin get confirmed
    payment: 6 # a payment transaction on Bitcoin get confirmed
    cold: 6 # a cold storage transaction on Bitcoin get confirmed
    manual: 6 # a manual transaction on Bitcoin get confirmed
  tssChainCode: ''
  derivationPath:
    -
cardano:
  networkType: 'mainnet' # Cardano network type [testnet, mainnet]
  chainNetwork: 'koios' # 'ogmios', 'koios' or 'blockfrost'
  blockfrost:
    projectId: ''
  koios:
    url: 'https://api.koios.rest/api/v1'
    timeout: 8
  bankPublicKey: '' # corresponding public key of lock address
  minUtxoValue: '3000000' # minimum lovelace for a Utxo (box)
  fee: '400000' # Cardano transaction fee
  txTtl: 9000 # Cardano transaction time-to-live
  confirmation: # required block confirmation
    observation: 120 # an observation transaction (lock transaction) on Cardano get confirmed
    payment: 120 # a payment transaction on Cardano get confirmed
    cold: 120 # a cold storage transaction on Cardano get confirmed
    manual: 120 # a manual transaction on Cardano get confirmed
  tssChainCode: 'CardanoChainCode'
ergo:
  networkType: 'mainnet' # Ergo network type [testnet, mainnet]
  chainNetwork: 'explorer' # 'explorer' or 'node'
  explorer:
    url: 'https://api.ergoplatform.com/'
    timeout: 8
  node:
    url: ''
    timeout: 8
  minBoxValue: '300000' # minimum nano-erg for a box
  additionalErgOnPayment: '0' # additional erg payment for events that are targeted to Ergo
  fee: '1100000' # Ergo transaction fee
  confirmation: # required block confirmation
    observation: 20 # an observation transaction (lock transaction) on Ergo get confirmed
    event: 20 # an event trigger box get confirmed
    payment: 20 # a payment or reward distribution transaction on Ergo get confirmed
    cold: 20 # a cold storage transaction on Ergo get confirmed
    manual: 20 # a manual transaction on Ergo get confirmed
  initialHeight: 925000 # block scanner starting block height
  scannerInterval: 180 # scanner update interval
ethereum:
  networkType: 'mainnet' # Ethereum network type [testnet, mainnet]
  chainNetwork: 'rpc' # 'rpc'
  rpc:
    url: ''
    timeout: 8
    initialHeight: -1
    scannerInterval: 20
  maxParallelTx: 5 # maximum number of txs to be processed with the same nonce (note that only one of these transactions will be succeed)
  gasPriceSlippage: 50 # allowed slippage percentage for gas price
  gasLimitSlippage: 50 # allowed slippage percentage for gas limit
  gasLimitMultiplier: 3 # a multiplication of current gas limit will be used in txs
  gasLimitCap: 60000 # the maximum required gas limit that is allowed (the cap is used if required gas is higher)
  confirmation: # required block confirmation
    observation: 200 # an observation transaction (lock transaction) on Ethereum get confirmed
    payment: 200 # a payment transaction on Ethereum get confirmed
    cold: 200 # a cold storage transaction on Ethereum get confirmed
    manual: 200 # a manual transaction on Ethereum get confirmed
  tssChainCode: ''
  derivationPath:
    -
reward:
  emissionTokenId: ''
  emissionTokenName: ''
  emissionTokenDecimal: 0
  bridgeFeeRepoAddress: '' # guards address for receiving bridge fee of events
  emissionAddress: '' # guards address for receiving emitted tokens of events
  networkFeeRepoAddress: '' # guards address for receiving network fee of events
  watchersSharePercent: 50 # watchers share for event fees (payed in tokens or native token)
  watchersEmissionSharePercent: 0 # watchers share for event fees (payed in emission token)
tss:
  path: './bin/tss.exe' # path to tss executable file
  configPath: './bin/conf/conf.env'
  url: 'http://localhost'
  port: 9000
  parallelSign: 5 # the maximum number of messages that can be signed in a single round
  secret: ''
  pubs:
    - curvePub: '' # ECDSA
      edwardPub: '' # EdDSA
      curveShareId: ''
      edwardShareId: ''
p2p:
  addresses: # relay configs
    - peerId: ''
      address: ''
  bootstrapTimeout: 10 # timeout of connecting to bootstrap nodes (which are relays in our case)
  pubsubInterval: 10 # interval of publishing peer ids to the network for peer discovery
  apiCallbackTimeout: 8 # timeout of api calls which happen when subscribing a channel in dialer
  loggingInterval: 60 # interval of logging jobs
  messageSendingRetriesExponentialFactor: 5 # exponential factor for calculating message retries interval
  messageSendingRetriesMaxCount: 3 # number of retires before dropping a failed message
  peerIdFilePath: './peer-dialer.json'
  guardsCount: 30 # total number of guards in the network
  allowedStreamsPerGuard: 3 # the number of streams allowed for each guard connected
  relayReconnectionInterval: 30 # Interval of tries to re-connect a disconnected relay
  brokenTimeAllowed: 1200 # seconds allowed to be unstable
eventTimeout: 86400 # timeout for processing events
txSignTimeout: 300 # timeout for signing transactions
guard:
  mnemonic: ''
  configUpdateInterval: 180 # guards config box update interval (getting guards configs from the box in Ergo network)
contracts:
  addressesBasePath: './config/rosen/'
logs:
  - type: 'file' # [file, console]
    path: './logs/' # path to log files (only for rotateFile type)
    maxSize: '20m' # maximum size of each log file (20 MB) (only for rotateFile type)
    maxFiles: '14d' # maximum number of log files (14 days) (only for rotateFile type)
    level: 'info' # [debug, info, warn, error]
  - type: 'console'
    level: 'info'
coldStorage:
  startHour: 17 # start of cold storage transaction generation period
  endHour: 19 # end of cold storage transaction generation period
intervals:
  txProcessorInterval: 60
  timeoutProcessorInterval: 3600 # interval to check if events got timeout
  requeueWaitingEventsInterval: 21600 # interval for requeue events which are timeout
  minimumFeeUpdateInterval: 300
tokensPath: './config/rosen/tokens.json' # path to supported tokens of bridge
thresholdsPath: './config/thresholds.json' # path to thresholds of lock address tokens
database:
  type: 'sqlite' # options: postgres, sqlite
  path: './sqlite/guard.sqlite' # database path (for sqlite)
  # host: '' # database host (for postgres)
  # port: 5432 # database port (for postgres)
  # user: '' # database user (for postgres)
  # password: '' # database password (for postgres)
  # name: '' # database name (for postgres)
healthCheck:
  interval: 60 # health check update interval (in seconds)
  asset:
    erg:
      warnThreshold: 1000000000 # minimum recommended erg balance
      criticalThreshold: 100000000 # minimum required erg balance
    emissionToken:
      warnThreshold: 1000000000 # minimum recommended token balance
      criticalThreshold: 100000000 # minimum required token balance
    ada:
      warnThreshold: 2500000000 # minimum recommended ada balance
      criticalThreshold: 200000000 # minimum required ada balance
    btc:
      warnThreshold: 5000000 # minimum recommended btc balance
      criticalThreshold: 1000000 # minimum required btc balance
    eth:
      warnThreshold: '20000000000000000' # minimum recommended eth balance
      criticalThreshold: '4000000000000000' # minimum required eth balance
  ergoScanner:
    warnDifference: 5 # warning difference between existing and scanned blocks height
    criticalDifference: 20 # critical difference between existing and scanned blocks height
  ethereumScanner:
    warnDifference: 50 # warning difference between existing and scanned blocks height
    criticalDifference: 200 # critical difference between existing and scanned blocks height
  ergoNode:
    maxHeightDifference: 2 # maximum difference between header height and full height
    maxBlockTime: 1800 # maximum time to see a new block
    minPeerCount: 10 # minimum recommended peers
    maxPeerHeightDifference: 2 # maximum difference between peers and our node
  errorLog:
    maxAllowedCount: 1 # maximum allowed error log lines
    duration: 600 # error log duration time check
  warnLog:
    maxAllowedCount: 10 # maximum allowed error log lines
    duration: 600 # error log duration time check
  p2p:
    defectConfirmationTimeWindow: 120 # Time to wait after any peer disconnection
  txSignFailed:
    warnThreshold: 3
    criticalThreshold: 7
revenue:
  interval: 120 # revenue update interval
discordWebHookUrl: '' # Discord webhook url for sending notifications
notification:
  historyCleanupThreshold: 90000 # 1 day and 1 hour
  windowDurations:
    hasBeenUnstableForAWhile: 900
    hasBeenUnknownForAWhile: 900
    isStillUnhealthy: 900
