---
# all time related configs are in seconds (timeout, interval, ...)

api:
  port: 8080 # service deployment port
  host: 'localhost' # service listening host
  apiKeyHash: '' # blake2b hash of Api-Key
  jsonBodyLimit: 50
  isManualTxRequestActive: false
  allowedOrigins: [] # List of allowed origins for CORS headers
  maxRequestsPerMinute: 100_000

cardano:
  networkType: 'mainnet' # Cardano network type [testnet, mainnet]
  chainNetwork: 'koios' # 'ogmios', 'koios' or 'blockfrost'
  blockfrost:
    projectId: ''
  koios:
    url: 'https://api.koios.rest/api/v1'
    timeout: 8
  bankPublicKey: '' # corresponding public key of lock address
  minUtxoValue: '3000000' # minimum lovelace for a Utxo (box)
  fee: '400000' # Cardano transaction fee
  txTtl: 9000 # Cardano transaction time-to-live
  confirmation: # required block confirmation
    observation: 120 # an observation transaction (lock transaction) on Cardano get confirmed
    payment: 120 # a payment transaction on Cardano get confirmed
    cold: 120 # a cold storage transaction on Cardano get confirmed
    manual: 120 # a manual transaction on Cardano get confirmed
  coldStorageAddress: ''
  tssChainCode: 'CardanoChainCode'
ergo:
  networkType: 'mainnet' # Ergo network type [testnet, mainnet]
  chainNetwork: 'explorer' # 'explorer' or 'node'
  explorer:
    url: 'https://api.ergoplatform.com/'
    timeout: 8
  node:
    url: ''
    timeout: 8
  minBoxValue: '300000' # minimum nano-erg for a box
  additionalErgOnPayment: '0' # additional erg payment for events that are targeted to Ergo
  fee: '1100000' # Ergo transaction fee
  confirmation: # required block confirmation
    observation: 20 # an observation transaction (lock transaction) on Ergo get confirmed
    event: 20 # an event trigger box get confirmed
    payment: 20 # a payment or reward distribution transaction on Ergo get confirmed
    cold: 20 # a cold storage transaction on Ergo get confirmed
    manual: 20 # a manual transaction on Ergo get confirmed
  initialHeight: 925000 # block scanner starting block height
  scannerInterval: 180 # scanner update interval
  coldStorageAddress: ''
reward:
  bridgeFeeRepoAddress: '' # guards address for receiving bridge fee of events
  RSNEmissionAddress: '' # guards address for receiving emitted RSN of events
  networkFeeRepoAddress: '' # guards address for receiving network fee of events
  watchersSharePercent: 50 # watchers share for event fees (payed in tokens or native token)
  watchersRSNSharePercent: 0 # watchers share for event fees (payed in RSN token)
tss:
  path: './bin/tss.exe' # path to tss executable file
  configPath: './bin/conf/conf.env'
  url: 'http://localhost'
  port: 9000
  timeout: 8 # connection timeout for tss API
  secret: ''
  ks:
    - ''
  curvePublicKeys: # ECDSA
    - ''
  edwardPublicKeys: # EdDSA
    - ''
p2p:
  addresses: # relay configs
    - peerId: ''
      address: ''
  bootstrapTimeout: 10 # timeout of connecting to bootstrap nodes (which are relays in our case)
  pubsubInterval: 10 # interval of publishing peer ids to the network for peer discovery
  apiCallbackTimeout: 8 # timeout of api calls which happen when subscribing a channel in dialer
  loggingInterval: 60 # interval of logging jobs
  messageSendingRetriesExponentialFactor: 5 # exponential factor for calculating message retries interval
  messageSendingRetriesMaxCount: 3 # number of retires before dropping a failed message
  peerIdFilePath: './peer-dialer.json'
  guardsCount: 30 # total number of guards in the network
  allowedStreamsPerGuard: 3 # the number of streams allowed for each guard connected
  relayReconnectionInterval: 30 # Interval of tries to re-connect a disconnected relay
  brokenTimeAllowed: 1200 # seconds allowed to be unstable
eventTimeout: 86400 # timeout for processing events
txSignTimeout: 300 # timeout for signing transactions
guard:
  mnemonic: ''
  configUpdateInterval: 180 # guards config box update interval (getting guards configs from the box in Ergo network)
contracts:
  addressesBasePath: './config/rosen/'
logs:
  - type: 'file' # [file, console]
    path: './logs/' # path to log files (only for rotateFile type)
    maxSize: '20m' # maximum size of each log file (20 MB) (only for rotateFile type)
    maxFiles: '14d' # maximum number of log files (14 days) (only for rotateFile type)
    level: 'info' # [debug, info, warn, error]
  - type: 'console'
    level: 'info'
coldStorage:
  startHour: 17 # start of cold storage transaction generation period
  endHour: 19 # end of cold storage transaction generation period
intervals:
  txProcessorInterval: 180
  timeoutProcessorInterval: 3600 # interval to check if events got timeout
  requeueWaitingEventsInterval: 43200 # interval for requeue events which are timeout
  minimumFeeUpdateInterval: 300
tokensPath: './config/rosen/tokens.json' # path to supported tokens of bridge
thresholdsPath: './config/thresholds.json' # path to thresholds of lock address tokens
discordWebHookUrl: '' # Discord webhook url for sending notifications
database:
  type: 'sqlite' # options: postgres, sqlite
  path: './sqlite/guard.sqlite' # database path (for sqlite)
  # host: '' # database host (for postgres)
  # port: 5432 # database port (for postgres)
  # user: '' # database user (for postgres)
  # password: '' # database password (for postgres)
  # name: '' # database name (for postgres)
healthCheck:
  interval: 60 # health check update interval (in seconds)
  asset:
    erg:
      warnThreshold: 1000000000 # minimum recommended erg balance
      criticalThreshold: 100000000 # minimum required erg balance
    rsn:
      warnThreshold: 1000000000 # minimum recommended erg balance
      criticalThreshold: 100000000 # minimum required erg balance
    ada:
      warnThreshold: 2500000000 # minimum recommended erg balance
      criticalThreshold: 200000000 # minimum required erg balance
  ergoScanner:
    warnDifference: 2 # warning difference between existing and scanned blocks height
    criticalDifference: 100 # critical difference between existing and scanned blocks height
  ergoNode:
    maxHeightDifference: 2 # maximum difference between header height and full height
    maxBlockTime: 1800 # maximum time to see a new block
    minPeerCount: 10 # minimum recommended peers
    maxPeerHeightDifference: 2 # maximum difference between peers and our node
  errorLog:
    maxAllowedCount: 2 # maximum allowed error log lines
    duration: 100 # error log duration time check
  p2p:
    defectConfirmationTimeWindow: 120 # Time to wait after any peer disconnection
revenue:
  interval: 120 # revenue update interval
keygen: # only set when you want to start keygen process
  active: false # set true to start keygen process on startup
  guards: 0 # total number of guards
  threshold: 0 # signing threshold (at least threshold + 1 guards are required)
  algorithm: eddsa # keygen algorithm. only eddsa supported
