name: Build and Push Docker Image
on:
  release:
    types:
      - created

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions:
          - latest
          - ${{ github.ref_name }}

    steps:   
      - name: Checkout the Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
     
      - name: Download Release From tss-api
        uses: dsaltares/fetch-gh-release-asset@1.1.1
        with:
          repo: 'rosen-bridge/tss-api'
          version: 'latest'
          regex: true
          file: "rosenTss-*"
          target: "./bin/"

      - name: Fetch Latest Version of Contract
        id: version
        run: echo "download_version=$(echo $(curl -s https://api.github.com/repos/rosen-bridge/contract/releases) | jq -r 'max_by(.published_at).name')" >> $GITHUB_OUTPUT

      - name: Download tokensMap from contract
        uses: dsaltares/fetch-gh-release-asset@1.1.1
        with:
          repo: 'rosen-bridge/contract'
          version: 'tags/${{ steps.version.outputs.download_version }}'
          regex: true
          file: 'tokensMap-${{ secrets.RELEASE_NAME }}-${{ steps.version.outputs.download_version }}.json'
          target: './config/'

      - name: Download contracts-cardano from contract
        uses: dsaltares/fetch-gh-release-asset@1.1.1
        with:
          repo: 'rosen-bridge/contract'
          version: 'tags/${{ steps.version.outputs.download_version }}'
          regex: true
          file: 'contracts-cardano-${{ secrets.RELEASE_NAME }}-${{ steps.version.outputs.download_version }}.json'
          target: './config/rosen/'

      - name: Download contracts-ergo from contract
        uses: dsaltares/fetch-gh-release-asset@1.1.1
        with:
          repo: 'rosen-bridge/contract'
          version: 'tags/${{ steps.version.outputs.download_version }}'
          regex: true
          file: 'contracts-ergo-${{ secrets.RELEASE_NAME }}-${{ steps.version.outputs.download_version }}.json'
          target: './config/rosen/'

      - name: Move the Files
        run: |
          mv ./docker/Dockerfile ./
          mv ./docker/production.yml ./config
          mv ./bin/rosenTss-* ./bin/rosenTss
          mv ./config/tokensMap-${{ secrets.RELEASE_NAME }}-${{ steps.version.outputs.download_version }}.json ./config/tokens.json
          mv ./config/rosen/contracts-cardano-${{ secrets.RELEASE_NAME }}-${{ steps.version.outputs.download_version }}.json ./config/rosen/contracts-cardano-mainnet.json
          mv ./config/rosen/contracts-ergo-${{ secrets.RELEASE_NAME }}-${{ steps.version.outputs.download_version }}.json ./config/rosen/contracts-ergo-mainnet.json

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ts-guard-service:${{ matrix.versions }}
