name: Build and Push Docker Image
on:
  release:
    types:
      - created

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions:
          - latest
          - ${{ github.ref_name }}

    steps:   
      - name: Checkout the Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
     
      - name: Download Release From tss-api
        id: download_libmicroros
        uses: dsaltares/fetch-gh-release-asset@1.1.1
        with:
          repo: 'rosen-bridge/tss-api'
          version: 'latest'
          regex: true
          file: "rosenTss-*"
          target: "./bin/rosenTss"

      - name: Move the Files
        run: |
          mv ./docker/Dockerfile ./
          mv ./docker/production.yml ./config

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ts-guard-service:${{ matrix.versions }}
